# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 6080
  connection-timeout: 5000ms
  servlet:
    context-path: /hm

spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    #是否开启redis缓存  true开启   false关闭
    open: true
    database: 1
    host: localhost
    port: 6379
    password:
    #连接超时时长（毫秒）
    timeout: 6000ms
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://localhost:3306/jeecg_dq?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 12345
      second:  #数据源2
        url: jdbc:mysql://localhost:3306/jeecg_dq?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 12345
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.renren.modules.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

renren:
  redis:
    open: false
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

#日志
logging:
  path: C:\Log_dq

#配置
us:
  cooperation:
    weChatOpenIdUrl: https://api.weixin.qq.com/sns/oauth2/access_token?grant_type=authorization_code
    weChatAppid: wxccfd726d286bca91
    weChatSecret: 5b09aab1013e54c261373d2fe0f1fe16
    weChatInfoUrl: https://api.weixin.qq.com/sns/userinfo?lang=zh_CN
    qqTokenUrl: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code
    qqClientId: 101474222
    qqClientSecret: 89b6fd82cd2aedee1c6567ca9d15e0de
    qqRedirectUri: http://www.dq-city.com/pages/login/login.html
    qqOpenIdUrl: https://graph.qq.com/oauth2.0/me
  icon:
    path: http://www.dq-city.com/jeecg/
  eid:
    content: eidLogin
    displayed: 注册
    returnUrl: http://www.dq-city.com/hm/api/meth/callback
  img:
    uploadImg: \\apache-tomcat-8.5.24-dq\\webapps\\hmPhotos\\upload
    dirTemp: \\apache-tomcat-8.5.24-dq\\webapps\\hmPhotos\\upload
    url: http://www.dq-city.com/hmPhotos/
  card:
    idCard: 2c908105657e0d7a01657e30fef8001f
    idCardPrefix: 622623
    trafficCard: 8ab3935865adf3fc0165b2910f0d000e
    trafficCardPrefix: 100100
  pay:
    mchId: 10000000
    reqKey: M86l522AV6q613Ii4W6u8K48uW8vM1N6bFgyv769220MdYe9u37N4y7rI5mQ
    repKey: Hpcl522AV6q613KIi46u6g6XuW8vM1N8bFgyv769770MdYe9u37M4y7rIpl8
    createOrderUrl: http://221.207.166.30:3020/api/pay/create_order?
    notifyUrl: http://www.dq-city.com/hm/api/pay/orderNotify
  bus:
    busUrl: https://restapi.amap.com/v3/direction/transit/integrated?
    geocodeUrl: http://restapi.amap.com/v3/geocode/geo?
    distanceUrl: http://restapi.amap.com/v3/distance?
    key: 50a751269e0cdc535921a65e8705a292
    output: josn
    city: 大庆市
  qrcode:
    size: 300
    expireTime: 300000
    path: C:\apache-tomcat-8.5.24-dq\webapps\hmPhotos\qrcode
    url: http://www.dq-city.com/hmPhotos/qrcode/
    logoWidth: 60
    logoHeight: 60
    logoPath: C:\logo_dq\logo.png

#云存储
fs:
  appUrl: http://221.207.166.30:9091/apps/add